use std::{
    fs::File,
    path::{Path, PathBuf},
};

use crate::{config_gen::Config, encryption::process_file::Metadata};

pub fn get_input_file(program_cfg: &Config) -> Result<File, String> {
    // Open input file and create output file
    let working_file = match File::open(&program_cfg.fp_in) {
        Ok(f) => {
            println!("File found.");
            f
        }
        Err(_) => {
            return Err(format!(
                "Could not find file: {}.",
                &program_cfg.fp_in.to_string_lossy()
            ));
        } // Convert it to a string so we dont have to use debug formatting
    };

    return Ok(working_file);
}

pub fn create_output_file(program_cfg: &Config) -> Result<File, String> {
    let mut default_out_file_name = program_cfg.in_file_name.clone();
    default_out_file_name.push_str(".rsa");
    let default_out_file = std::env::current_dir().unwrap().join(default_out_file_name); // All files generated by this program are .rsa files

    let output_filepath = match &program_cfg.fp_out {
        Some(path) => path.with_extension("rsa"),
        None => default_out_file,
    }
    .clone();

    let output_file = match File::create(&output_filepath) {
        Ok(f) => f,
        Err(e) => {
            return Err(format!(
                "Could not create output file at: [{}] Reason: {}",
                output_filepath.to_string_lossy().into_owned(),
                e
            ));
        }
    };

    return Ok(output_file);
}

pub fn create_output_file_from_metadata(
    program_cfg: &Config,
    file_metadata: &Metadata,
) -> Result<File, String> {
    // Default output file from the metadata set in the current directory
    let mut default_folder = std::env::current_dir().unwrap();
    let mut out_path = default_folder.clone();

    // If the config does NOT provide a set output path OR there is no parent folder THEN use default folder
    match &program_cfg.fp_out {
        Some(fp) => {
            // output flag has no parent folder:
            let parent_folder = fp.parent().unwrap_or(&default_folder);
            if parent_folder.to_string_lossy().into_owned() == "" {
                out_path = fp.to_path_buf();
            } else {
                out_path = fp.to_path_buf();
                // NOTE: this will make out_path INCLUDE the file name aswell,
                // but doing it this way means we can use.set_file_name and similar to replace the file name and extensions
                // which is better readablility than doing .join(filename) as .join is meant for folder joining really
            }
        }
        None => {
            // this gets overriden by .set_file_name down below
            out_path = out_path.join("placeholder");
        }
    }

    // By default write in the file name and extension from the metadata
    out_path.set_file_name(&file_metadata.file_name);
    match &file_metadata.file_ext {
        Some(e) => {
            out_path.set_extension(e);
        }
        None => {}
    }

    // If name or ext is provided via config, then overwrite with that
    if let Some(name) = &program_cfg.out_file_name {
        set_file_stem(&mut out_path, name);
    }

    if let Some(ext) = &program_cfg.out_file_ext {
        out_path.set_extension(ext);
    }

    let output_file = match File::create(&out_path) {
        Ok(f) => f,
        Err(e) => {
            return Err(format!(
                "Could not create output file at: [{}] Reason: {}",
                out_path.to_string_lossy().into_owned(),
                e
            ));
        }
    };

    return Ok(output_file);
}

fn set_file_stem(path: &mut PathBuf, new_stem: &str) {
    let new_name = match path.extension() {
        Some(ext) => format!("{new_stem}.{}", ext.to_string_lossy()),
        None => new_stem.to_string(),
    };

    path.set_file_name(new_name);
}
