use std::fs::File;

use crate::config_gen::Config;

pub fn get_input_file(program_cfg: &Config) -> Result<File, String> {
    // Open input file and create output file
    let working_file = match File::open(&program_cfg.fp_in) {
        Ok(f) => {
            println!("File found.");
            f
        }
        Err(_) => {
            return Err(format!(
                "Could not find file: {}.",
                &program_cfg.fp_in.to_string_lossy()
            ));
        } // Convert it to a string so we dont have to use debug formatting
    };

    return Ok(working_file);
}

pub fn create_output_file(program_cfg: &Config) -> Result<File, String> {
    let mut default_out_file_name = program_cfg.file_name.clone();
    default_out_file_name.push_str(".rsa");
    let default_out_file = std::env::current_dir().unwrap().join(default_out_file_name); // All files generated by this program are .rsa files

    let output_filepath = match &program_cfg.fp_out {
        Some(path) => path.with_extension("rsa"),
        None => default_out_file,
    }
    .clone();

    let mut output_file = match File::create(&output_filepath) {
        Ok(f) => f,
        Err(e) => {
            return Err(format!(
                "Could not create output file at: [{}] Reason: {}",
                output_filepath.to_string_lossy().into_owned(), e
            ));
        }
    };

    return Ok(output_file);
}
