use std::{
    fs::File,
    io::{BufReader, BufWriter, Read, Write},
};

use crate::{
    config_gen::Config,
    encryption::{self, ceaser_cipher::decrypt_data_chunk},
};

// Takes data chunks from the input file and performs the encryption on them, and then writes them to the output file.
pub fn encrypt_file(in_file: &File, out_file: &mut File, cfg: &Config) -> Result<(), String> {
    let mut data_buffer: Vec<u8> = vec![0u8; cfg.chunk_size];
    let mut reader = BufReader::new(in_file);
    let mut iter_count = 0;

    // With "no limits", we use usize max just as a final safety net still
    // 1_000_000 default limit with default chunk size of 1kb means default limit is a 1gb file which is reasonable
    let iter_limit = { if cfg.no_max { usize::MAX } else { 1_000_000 } };

    // First write in the metadata chunk, which is just file name and extension:

    let mut metadata: Vec<u8> = generate_metadata_bytes(&cfg)?;
    let metadata_bytes = write_to_output(out_file, &metadata)?;
    println!("Wrote {} bytes of metadata", metadata_bytes);

    while iter_count < iter_limit {
        // When there are 0 bytes left to read that means EOF and we should exit
        let bytes_read = reader.read(&mut data_buffer).unwrap();
        if bytes_read == 0 {
            break; // EOF
        }

        let processed_data =
            encryption::ceaser_cipher::encrypt_data_chunk(&data_buffer[0..bytes_read], &cfg);

        let bytes_written = write_to_output(out_file, &processed_data)?;
        println!("{} bytes written to file", bytes_written);

        // Ensure at minimum we are writing the same number of bytes as we read
        debug_assert!(bytes_written <= bytes_read, "Data was lost!");

        iter_count += 1;
        println!("Iteration: {}", iter_count)
    }

    return Ok(());
}

// File storage layout will be [metadata_len][metadata_chunk][data...]
// metadata_len is a single byte at the start telling us how long the metadata chunk is
// metadata_chunk will be the whole filestring "ThisIsAFile.txt", encrypted via same algorithm as the data
// now that string can be arbitrary size compared to the other chunks of the program, as it should never be overly large
// after that, we insert a singular null to seperate the metadata from the data
// then rest of file is read as data via chunking

/// Generates a byte array for the provided file metadata in the program config
///
/// Generated byte array is formatted in 2 sections<br/>
/// [metadata_len] - Single byte which is the length of the encrypted metadata chunk <br/>
/// [metadata] - [array of bytes containing the encrypted metadata]
///
/// # Arguments
///
/// * `cfg` - The program config
///     
/// # Returns
///
/// * [`Vec<u8>`] - Vec of bytes. Formatted: [metadata_Length][metadata]
/// * [`String`] - Error message
fn generate_metadata_bytes(cfg: &Config) -> Result<Vec<u8>, String> {
    let mut output: Vec<u8> = Vec::new();

    // Calculate metadata length
    let mut len = 0;
    len += cfg.file_name.len();
    match &cfg.file_ext {
        Some(x) => {
            len += x.len();
            len += 1 // Account for the '.'
        }
        None => {}
    };

    if len > 255 {
        return Err(format!("File metadata is too long"));
    } else {
        output.push(len as u8);
    }

    // write name
    output.extend_from_slice(cfg.file_name.as_bytes());

    // write cfg if applicable
    match &cfg.file_ext {
        Some(v) => {
            output.push('.' as u8);
            output.extend_from_slice(v.as_bytes());
        }
        None => {}
    }

    return Ok(output);
}

pub fn decrypt_file(in_file: &File, out_file: &mut File, cfg: &Config) -> Result<(), String> {
    let mut data_buffer: Vec<u8> = vec![0u8; cfg.chunk_size];
    let mut reader = BufReader::new(in_file);
    let mut iter_count = 0;
    let mut metadata_complete = false;

    // With "no limits", we use usize max just as a final safety net still
    // 1_000_000 default limit with default chunk size of 1kb means default limit is a 1gb file which is reasonable
    let iter_limit = { if cfg.no_max { usize::MAX } else { 1_000_000 } };

    while iter_count < iter_limit {
        let bytes_read = reader.read(&mut data_buffer).unwrap();
        if bytes_read == 0 {
            break; //EOF
        }

        let processed_chunk =
            encryption::ceaser_cipher::decrypt_data_chunk(&data_buffer[0..bytes_read], &cfg);

        if !metadata_complete {
            //extract_metadata(&mut processed_chunk, &cfg);
        }
    }

    return Ok(());
}

struct Metadata {
    has_ext: bool,
    file_name: String,
    file_ext: Option<String>,
}

pub fn extract_metadata(
    reader: &mut BufReader<&File>,
    data: &mut [u8],
    cfg: &Config,
) -> Result<(), String> {
    // Read first byte to know how long metadata chunk is
    // first byte is never encrypted
    let mut byte_buffer = [0u8; 1];
    reader.read_exact(&mut byte_buffer);

    let mut metadata_buffer = vec![0u8; byte_buffer[0] as usize];
    reader.read_exact(&mut metadata_buffer);

    let processed_metadata = decrypt_data_chunk(&metadata_buffer, &cfg);

    let filename = match String::from_utf8(processed_metadata) {
        Ok(s) => s,
        Err(e) => return Err(e.to_string()),
    };

    return Ok(());
}

pub fn write_to_output(out_file: &mut File, data: &[u8]) -> Result<usize, String> {
    let res = out_file.write(data);

    // There's probaly some .SolveEverything() extension that does this but whatever no harm in doing it manually compiler can optimise this
    match res {
        Ok(x) => return Ok(x),
        Err(x) => return Err(x.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use std::{fs::File, path::PathBuf};

    use crate::{config_gen::Config, encryption::process_file::generate_metadata_bytes};

    #[test]
    fn test_encrypt_file(){
       // TODO
    }

    #[test]
    fn test_gen_metadata() {
        let mut cfg: Config = Config {
            encryption_mode: false,
            fp_in: PathBuf::new(),
            fp_out: None,
            file_name: "FileThatExistsTxt".to_string(),
            file_ext: Some("txt".to_string()),
            chunk_size: 1024,
            no_max: false,
        };

        // Typical input
        let expected = vec![
            21, 70, 105, 108, 101, 84, 104, 97, 116, 69, 120, 105, 115, 116, 115, 84, 120, 116, 46,
            116, 120, 116,
        ];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "Standard metadata test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // Blank file name
        cfg.file_name = "".to_string();
        let expected = vec![4, 46, 116, 120, 116];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "Blank filename metadata test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // No Extension
        cfg.file_name = "FileThatExistsTxt".to_string();
        cfg.file_ext = None;
        let expected = vec![
            17, 70, 105, 108, 101, 84, 104, 97, 116, 69, 120, 105, 115, 116, 115, 84, 120, 116,
        ];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "No extension test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // Too long filename
        cfg.file_name = "1234567890".repeat(26);
        cfg.file_ext = Some("png".to_string());
        let actual = generate_metadata_bytes(&cfg);
        assert!(
            actual.is_err(),
            "Filename too long test:\nDid not err with input: [file_name: {}, file_ext: {}]\nAnd generated output: {:?}",
            cfg.file_name,
            cfg.file_ext.unwrap(),
            actual.unwrap()
        );
    }
}
