use std::{
    fs::File,
    io::{BufReader, BufWriter, Read, Write},
};

use crate::{
    config_gen::Config,
    encryption::{self, ceaser_cipher::decrypt_data_chunk},
};

// Takes data chunks from the input file and performs the encryption on them, and then writes them to the output file.
pub fn encrypt_file(in_file: &File, out_file: &mut File, cfg: &Config) -> Result<(), String> {
    let mut data_buffer: Vec<u8> = vec![0u8; cfg.chunk_size];
    let mut reader = BufReader::new(in_file);
    let mut iter_count = 0;

    // With "no limits", we use usize max just as a final safety net still
    // 1_000_000 default limit with default chunk size of 1kb means default limit is a 1gb file which is reasonable
    let iter_limit = { if cfg.no_max { usize::MAX } else { 1_000_000 } };

    // First write in the metadata chunk, which is just file name and extension:

    let mut metadata: Vec<u8> = generate_metadata_bytes(&cfg)?;
    let metadata_bytes = write_to_output(out_file, &metadata)?;
    println!("Wrote {} bytes of metadata", metadata_bytes);

    while iter_count < iter_limit {
        // When there are 0 bytes left to read that means EOF and we should exit
        let bytes_read = reader.read(&mut data_buffer).unwrap();
        if bytes_read == 0 {
            break; // EOF
        }

        let processed_chunk =
            encryption::ceaser_cipher::encrypt_data_chunk(&data_buffer[0..bytes_read], &cfg);

        let bytes_written = write_to_output(out_file, &processed_chunk)?;
        println!("{} bytes written to file", bytes_written);

        // Ensure at minimum we are writing the same number of bytes as we read
        debug_assert!(bytes_written <= bytes_read, "Data was lost!");

        iter_count += 1;
        println!("Iteration: {}", iter_count)
    }

    return Ok(());
}

// File storage layout will be [metadata_len][metadata_chunk][data...]
// metadata_len is a single byte at the start telling us how long the metadata chunk is
// metadata_chunk will be the whole filestring "ThisIsAFile.txt", encrypted via same algorithm as the data
// now that string can be arbitrary size compared to the other chunks of the program, as it should never be overly large
// after that, we insert a singular null to seperate the metadata from the data
// then rest of file is read as data via chunking

/// Generates a byte array for the provided file metadata in the program config
///
/// Generated byte array is formatted in 2 sections<br/>
/// [metadata_len] - Single byte which is the length of the encrypted metadata chunk <br/>
/// [metadata] - [array of bytes containing the encrypted metadata]
///
/// # Arguments
///
/// * `cfg` - The program config
///     
/// # Returns
///
/// * [`Vec<u8>`] - Vec of bytes. Formatted: [metadata_Length][metadata]
/// * [`String`] - Error message
fn generate_metadata_bytes(cfg: &Config) -> Result<Vec<u8>, String> {
    let mut output: Vec<u8> = Vec::new();
    let mut name_chunk: Vec<u8> = Vec::new();

    // Calculate metadata length
    let mut len = 0;
    len += cfg.in_file_name.len();
    match &cfg.in_file_ext {
        Some(x) => {
            len += x.len();
            len += 1 // Account for the '.'
        }
        None => {}
    };

    if len > 255 {
        return Err(format!("File metadata is too long"));
    } else {
        output.push(len as u8);
    }

    // write name
    name_chunk.extend_from_slice(cfg.in_file_name.as_bytes());

    // write cfg if applicable
    match &cfg.in_file_ext {
        Some(ext) => {
            name_chunk.push('.' as u8);
            name_chunk.extend_from_slice(ext.as_bytes());
        }
        None => {}
    }
    
    let encrypted_result = encryption::ceaser_cipher::encrypt_data_chunk(&name_chunk, &cfg);
    output.extend_from_slice(&encrypted_result);

    return Ok(output);
}

pub fn decrypt_file(
    in_reader: &mut BufReader<File>,
    out_file: &mut File,
    cfg: &Config,
) -> Result<(), String> {
    let mut data_buffer: Vec<u8> = vec![0u8; cfg.chunk_size];
    let mut iter_count = 0;

    // With "no limits", we use usize max just as a final safety net still
    // 1_000_000 default limit with default chunk size of 1kb means default limit is a 1gb file which is reasonable
    let iter_limit = { if cfg.no_max { usize::MAX } else { 1_000_000 } };

    while iter_count < iter_limit {
        let bytes_read = in_reader.read(&mut data_buffer).unwrap();
        if bytes_read == 0 {
            break; //EOF
        }

        let processed_chunk =
            encryption::ceaser_cipher::decrypt_data_chunk(&data_buffer[0..bytes_read], &cfg);


        let bytes_written = write_to_output(out_file, &processed_chunk)?;
        println!("{} bytes written to file", bytes_written);

        // Ensure at minimum we are writing the same number of bytes as we read
        debug_assert!(bytes_written <= bytes_read, "Data was lost!");

        iter_count += 1;
        println!("Iteration: {}", iter_count);
        iter_count += 1;
    }

    return Ok(());
}

pub struct Metadata {
    pub file_name: String,
    pub file_ext: Option<String>,
}

impl Metadata {
    pub fn new(name: String, ext: Option<String>) -> Self {
        return Metadata {
            file_name: (name),
            file_ext: (ext),
        };
    }
}

pub fn extract_metadata(reader: &mut BufReader<File>, cfg: &Config) -> Result<Metadata, String> {
    // Read first byte to know how long metadata chunk is
    // first byte is never encrypted
    let mut byte_buffer = [0u8; 1];
    reader.read_exact(&mut byte_buffer);

    let mut metadata_buffer = vec![0u8; byte_buffer[0] as usize];
    reader.read_exact(&mut metadata_buffer);

    let processed_metadata = decrypt_data_chunk(&metadata_buffer, &cfg);

    let mut full_filename = match String::from_utf8(processed_metadata) {
        Ok(s) => s,
        Err(e) => return Err(e.to_string()),
    };

    let ext_index = scan_backwards(&full_filename, '.');

    let mut file_name = String::new();
    let mut file_ext: Option<String> = None;

    // If we found the . for the extension, split the filename at that
    // otherwise there must be no extension so we use the whole thing as the filename
    match ext_index {
        Some(i) => {
            // Split the filename at the '.' and remove the '.' from the result
            let mut t = full_filename.split_off(i);
            t.remove(0);
            file_ext = Some(t);


            file_name = full_filename;
        }
        None => {
            file_name = full_filename;
        }
    }

    return Ok(Metadata::new(file_name, file_ext));
}

/// Scans a target string for a given character starting from the end and moving towards the start
///
/// # Arguments
///
/// * `data` - The target string to search through
/// * `target` - The character being searched for
///
/// # Returns
///
/// * [`usize`] - the found index of the target
/// * [`None`] - if the target could not be found
///
/// # Examples
/// ```
/// // Find starting index of file extension
/// let file_name = "target.txt".to_String();
/// let index = scan_backwards(&file_name, '.');
///
/// assert_eq!(index, 7);
/// ```
fn scan_backwards(data: &String, target: char) -> Option<usize> {
    let mut arr = data.char_indices();

    while let Some(c) = arr.next_back() {
        if c.1 == target {
            return Some(c.0);
        }
    }

    return None;
}

pub fn write_to_output(out_file: &mut File, data: &[u8]) -> Result<usize, String> {
    let res = out_file.write(data);

    // There's probaly some .SolveEverything() extension that does this but whatever no harm in doing it manually compiler can optimise this
    match res {
        Ok(x) => return Ok(x),
        Err(x) => return Err(x.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use std::{fs::File, path::PathBuf};

    use crate::{config_gen::Config, encryption::process_file::generate_metadata_bytes};

    #[test]
    fn test_encrypt_file() {
        // TODO
    }

    #[test]
    fn test_gen_metadata() {
        let mut cfg: Config = Config {
            encryption_mode: false,
            fp_in: PathBuf::new(),
            fp_out: None,
            in_file_name: "FileThatExistsTxt".to_string(),
            in_file_ext: Some("txt".to_string()),
            out_file_name: None,
            out_file_ext: None,
            chunk_size: 1024,
            no_max: false,
        };

        // Typical input
        let expected = vec![
            21, 70, 105, 108, 101, 84, 104, 97, 116, 69, 120, 105, 115, 116, 115, 84, 120, 116, 46,
            116, 120, 116,
        ];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "Standard metadata test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // Blank file name
        cfg.in_file_name = "".to_string();
        let expected = vec![4, 46, 116, 120, 116];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "Blank filename metadata test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // No Extension
        cfg.in_file_name = "FileThatExistsTxt".to_string();
        cfg.in_file_ext = None;
        let expected = vec![
            17, 70, 105, 108, 101, 84, 104, 97, 116, 69, 120, 105, 115, 116, 115, 84, 120, 116,
        ];
        let actual = generate_metadata_bytes(&cfg).unwrap();
        assert!(
            expected == actual,
            "No extension test:\nExpected value generated: {:?}\nActual value generated: {:?}",
            expected,
            actual
        );

        // Too long filename
        cfg.in_file_name = "1234567890".repeat(26);
        cfg.in_file_ext = Some("png".to_string());
        let actual = generate_metadata_bytes(&cfg);
        assert!(
            actual.is_err(),
            "Filename too long test:\nDid not err with input: [file_name: {}, file_ext: {}]\nAnd generated output: {:?}",
            cfg.in_file_name,
            cfg.in_file_ext.unwrap(),
            actual.unwrap()
        );
    }
}
